### ISSUE TITLE
Discuss folder and project structures

### ISSUE THREAD

**Issue by XX-NF-XX** [RPVanarx/WIMPbot#11]
Продолжу на русском, чтобы всем было понятнее.

Пока думал над созданием списка задач для АПИ под фронтенд, у меня в голове возникло несколько нестыковок в организации проекта, а именно: что и где должно храниться, как оно должно совместно работать, и не будут ли наши "сервисы" друг другу мешать.

_Суть:_ 

Есть ядро приложения (т.н. business logic) - самая главная часть проекта, живет вместе с БД враппером и самой БД. По сути это всё единая самостоятельная сущность, которая будет являть собою уже вполне рабочую еденицу и предоставлять API для доступа к данным. К ядру в свою очередь будет подключаться каждый "сервис" и брать/отдавать что кому нужно. Плюс к этому АПИ под фронт будет передавать данные дальше на фронт. В итоге у нас получается 5 составных частей: ядро, 2 бота, фронт АПИ и собственно сам фронт.

_Отсюда такие вопросы:_
- как это всё разложить по отдельным папкам чтобы имзенения в одной части не затрагивали других частей?
- как организуем документацию каждого модуля?
- как организовать систему коммитов чтобы мы не натворили плапши из коммитов?

**Comment by XX-NF-XX** [comment]
>     * как это всё разложить по отдельным папкам чтобы имзенения в одной части не затрагивали других частей?
Нашел [пример](https://github.com/kriasoft/Folder-Structure-Conventions), но не уверенн, что он нам очень поможет

>     * как организуем документацию каждого модуля?
Например можно складывать в папку **doc** прямо тут в репозитории.

**Comment by RPVanarx** [comment]
> * как организуем документацию каждого модуля?

Ось про це ще навіть не думав якщо чесно. Можна створити 1 доку прямо в основі репозиторія і кожен буде туди підтягувати опис створених модулів

**Comment by RPVanarx** [comment]
> * как организовать систему коммитов чтобы мы не натворили плапши из коммитов?

Моя пропозиція проста по цьому проекту, він у нас маленький, і пропоную тут не сильно забивати голову правильністю і красотою (це все прийде із досвідом), а більше зосередитися на виконанні.

**Comment by XX-NF-XX** [comment]
> Гадаю структура має бути такою - viber, telegram, api, sevices(вона ж бізнеслогіка), dbwrapper, config - це фолдери, а по файлах то app.js в якому будемо запускати свої апчики (а також в цьому файлі
> підключати dbCreate і dbConnect) тобто у вас має бути поставлена база, в дотенвах прописані власні юзери і паролі доступу до бази, і далі підтягувати цей код в app.js із перевіркою "CREATE TABLE IF NOT EXIST" Щоб у кожного при запуску створювалися таблиці якшо їх ще нема, і можна було свій код тестити і т.д. Думаю так у нас модулі не будуть пересікатися, і взаємодіяти лише через бізнеслогіку
> 
> Якщо комусь потрібно щось додати в конфіг не питання, добавляєте і в себе підключаєте, якщо щось по логіці чи врапперу то просто пишете і ми вирішуємо як їх проапдейтити і т.д.

Мне кажется, что будет более проще/логичнее/лучше всё разделить. Чтобы конфиг у каждого свой был, чтобы части были независимы, таким образом мы обеспечим стабильность всей системы и не будет такого, что фронтенд изменил конфиг боту.
По поводу DB. Вот и первая дока - "как запустить бизнес логику".
